### ISSUE TITLE
When creating/altering a topic from MSAdmin, assign a set of standards to it

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/msadmin#40] opened 2018-11-08 18:46 UTC
When creating/altering a topic from MSAdmin, assign a set of standards to it, in a new table that associates standards to topics.

**Comment by IvonArroyo** [comment] 2018-11-08 18:48
You will also have to modify the probprobgrouptable as standards get assigned or deleted from topics.

**Comment by mohit-surana** [comment] 2018-12-16 02:51
Closing as a duplicate of #40.

**Closed by mohit-surana** 2018-12-16 02:51 UTC
